import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"

// Content data for each theory topic
const getTheoryContent = (slug: string) => {
    const content: Record<string, any> = {
        aerodynamics: {
            title: "Aerodynamics of Drone Flight",
            subtitle: "Understanding the core aerodynamic principles that govern multirotor and small fixed-wing drones.",
            sections: [
                {
                    id: "overview",
                    title: "Overview",
                    content: `
                        <p>This guide explains the core aerodynamic principles that govern multirotor and small fixed-wing drones. Each principle is essential for understanding how drones achieve controlled flight.</p>
                        <div class="bg-primary/10 border-l-4 border-primary p-4 my-6 rounded">
                            <strong>Quick summary:</strong> Drone flight is a balance of <em>thrust</em>, <em>lift</em>, <em>weight</em>, and <em>drag</em>, with stability and control handled through rotor thrust vectoring and flight controllers.
                        </div>
                    `
                },
                {
                    id: "forces",
                    title: "1. Forces on a Drone",
                    content: `
                        <p>Four primary forces act on a drone in flight:</p>
                        <ul class="space-y-2 my-4">
                            <li><strong>Thrust</strong> — generated by propellers/rotors pushing air downwards.</li>
                            <li><strong>Lift</strong> — for fixed-wing craft, lift comes from wings; for multirotors, lift equals rotor thrust component opposing gravity.</li>
                            <li><strong>Weight</strong> — gravitational pull of the drone (including payload).</li>
                            <li><strong>Drag</strong> — aerodynamic resistance caused by motion through air.</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">How they interact</h3>
                        <p>In hover, <strong>thrust = weight</strong>. For ascent, thrust > weight; for descent, thrust < weight. Horizontal motion increases drag and requires additional thrust components to overcome it.</p>
                    `
                },
                {
                    id: "lift",
                    title: "2. Lift and Rotor Aerodynamics",
                    content: `
                        <p>For multirotors, each rotor produces a pressure difference by accelerating air downwards — this generates an upward thrust per Newton's 3rd law. Key factors:</p>
                        <ul class="space-y-2 my-4">
                            <li><strong>Rotor disk area:</strong> Larger diameter rotors move more air at lower speed, improving efficiency.</li>
                            <li><strong>Tip speed:</strong> Higher tip speeds can increase thrust but also noise and compressibility losses at very high RPM.</li>
                            <li><strong>Blade pitch and airfoil:</strong> Blade shape controls the lift coefficient; small pitch changes affect thrust strongly.</li>
                        </ul>
                        <p class="italic mt-4">Useful relation (qualitative): Thrust ≈ (air density) × (disk area) × (induced velocity)².</p>
                    `
                },
                {
                    id: "drag",
                    title: "3. Drag, Profile & Induced Drag",
                    content: `
                        <p><strong>Profile drag</strong> comes from the shape and skin friction of the drone body and arms. <strong>Induced drag</strong> is a byproduct of creating lift/thrust — when you produce lift, you create vortices that cost energy.</p>
                        <ul class="space-y-2 my-4">
                            <li><strong>Minimize body frontal area</strong> and use smooth fairings to reduce profile drag.</li>
                            <li><strong>Lightweight frames</strong> help reduce required lift, but tradeoffs exist with structural stiffness.</li>
                        </ul>
                    `
                },
                {
                    id: "stability",
                    title: "4. Stability & Control",
                    content: `
                        <p>Stability is divided into three axes: <strong>pitch</strong>, <strong>roll</strong>, and <strong>yaw</strong>. Flight controllers use gyros/IMUs and PID loops to maintain attitude.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">How adjustment works</h3>
                        <ul class="space-y-2 my-4">
                            <li>To pitch forward, rear rotors increase thrust while front rotors decrease thrust.</li>
                            <li>Yaw is achieved by creating a torque imbalance (rotor spin directions matter).</li>
                            <li>Autonomous stability relies on sensor fusion (GPS, IMU, barometer, optical flow).</li>
                        </ul>
                    `
                },
                {
                    id: "manoeuvres",
                    title: "5. Flight Maneuvers & Energy Use",
                    content: `
                        <p>Aggressive maneuvers use more energy due to higher thrust requirements and increased drag. Efficient flight planning avoids unnecessary accelerations: keep steady cruise speed and gradual altitude changes.</p>
                        <ul class="space-y-2 my-4">
                            <li><strong>Hover:</strong> Highest sustained energy per unit time for small drones.</li>
                            <li><strong>Forward flight (fixed-wing):</strong> more efficient for long distances.</li>
                            <li><strong>Transitioning (VTOL):</strong> requires careful control during rotor-to-wing transition.</li>
                        </ul>
                    `
                },
                {
                    id: "equations",
                    title: "6. Advanced Aerodynamic Equations",
                    content: `
                        <p>To design efficient drones, we must quantify the forces at play. Here are the governing equations used in aeronautical engineering.</p>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Lift Equation</h3>
                        <div class="bg-muted p-4 rounded-md font-mono text-sm my-4">
                            L = ½ · ρ · v² · S · C<sub>L</sub>
                        </div>
                        <ul class="space-y-1 text-sm text-muted-foreground mb-6">
                            <li><strong>ρ (rho):</strong> Air density (1.225 kg/m³ at sea level)</li>
                            <li><strong>v:</strong> Velocity relative to the air</li>
                            <li><strong>S:</strong> Wing area (or Rotor Disk Area)</li>
                            <li><strong>C<sub>L</sub>:</strong> Coefficient of Lift (dependent on Angle of Attack α)</li>
                        </ul>

                        <h3 class="text-xl font-semibold mt-6 mb-3">Drag Decomposition</h3>
                        <p>Total Drag is the sum of Parasitic Drag and Induced Drag.</p>
                        <div class="bg-muted p-4 rounded-md font-mono text-sm my-4">
                            D<sub>total</sub> = D<sub>parasitic</sub> + D<sub>induced</sub><br><br>
                            D<sub>p</sub> = ½ · ρ · v² · S · C<sub>D0</sub><br>
                            D<sub>i</sub> = (2 · L²) / (ρ · v² · π · b² · e)
                        </div>
                        <p class="text-sm mt-2">Where <strong>b</strong> is wingspan and <strong>e</strong> is the Oswald efficiency number (typically 0.7-0.9).</p>

                        <h3 class="text-xl font-semibold mt-6 mb-3">Propeller Physics</h3>
                        <p>For multirotors, we use dimensionless coefficients to characterize propeller performance.</p>
                        <div class="bg-muted p-4 rounded-md font-mono text-sm my-4">
                            Thrust: T = C<sub>T</sub> · ρ · n² · D⁴<br>
                            Power: P = C<sub>P</sub> · ρ · n³ · D⁵
                        </div>
                        <p class="text-sm mt-2">Note the power law: <strong>Power scales with RPM cubed (n³)</strong>. This is why flying 10% faster requires ~33% more power.</p>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Figure of Merit (FM)</h3>
                        <p>A measure of hover efficiency (ideal power vs. actual power).</p>
                        <div class="bg-muted p-4 rounded-md font-mono text-sm my-4">
                            FM = T<sup>3/2</sup> / (P · √(2 · ρ · A))
                        </div>
                    `
                },
                {
                    id: "control-theory",
                    title: "7. Control Theory Implementation",
                    content: `
                        <p>How does physics translate to code? The Flight Controller runs a control loop (typically at 4kHz or 8kHz) to stabilize the drone.</p>

                        <h3 class="text-xl font-semibold mt-6 mb-3">The PID Controller</h3>
                        <p>A Proportional-Integral-Derivative controller corrects errors between the <em>desired</em> rotation rate (setpoint) and the <em>actual</em> rotation rate (gyro).</p>
                        
                        <pre class="bg-zinc-950 text-zinc-50 p-4 rounded-lg overflow-x-auto my-4 text-sm"><code>class PIDController {
    kp: number; ki: number; kd: number;
    integral: number = 0;
    prevError: number = 0;
    maxIntegral: number = 100; // Anti-windup limit

    update(setpoint: number, measured: number, dt: number): number {
        const error = setpoint - measured;
        
        // Proportional Term
        const P = this.kp * error;

        // Integral Term (with Anti-Windup)
        this.integral += error * dt;
        this.integral = Math.max(-this.maxIntegral, 
                        Math.min(this.maxIntegral, this.integral));
        const I = this.ki * this.integral;

        // Derivative Term (on Measurement to avoid kick)
        // D = -kd * (measured - prevMeasured) / dt
        // Simplified here for clarity:
        const derivative = (error - this.prevError) / dt;
        const D = this.kd * derivative;

        this.prevError = error;
        return P + I + D;
    }
}</code></pre>

                        <h3 class="text-xl font-semibold mt-6 mb-3">Motor Mixing</h3>
                        <p>The PID output (Roll, Pitch, Yaw) must be mixed with Throttle to determine individual motor speeds.</p>
                        <div class="bg-muted p-4 rounded-md font-mono text-sm my-4">
                            ⎡ M1 ⎤   ⎡ 1  1 -1 -1 ⎤   ⎡ Throttle ⎤<br>
                            ⎢ M2 ⎥ = ⎢ 1  1  1  1 ⎥ · ⎢ Pitch    ⎥<br>
                            ⎢ M3 ⎥   ⎢ 1 -1  1 -1 ⎥   ⎢ Roll     ⎥<br>
                            ⎣ M4 ⎦   ⎣ 1 -1 -1  1 ⎦   ⎣ Yaw      ⎦
                        </div>
                        <p class="text-sm mt-2">M1=FL, M2=FR, M3=BL, M4=BR (Standard Betaflight Quad X configuration).</p>
                    `
                },
                {
                    id: "sensor-fusion",
                    title: "8. Sensor Fusion Mathematics",
                    content: `
                        <p>A drone cannot rely on a single sensor. The Gyro drifts over time, and the Accelerometer is noisy due to vibrations.</p>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Complementary Filter</h3>
                        <p>We combine the high-frequency accuracy of the Gyro with the low-frequency stability of the Accelerometer.</p>
                        <div class="bg-muted p-4 rounded-md font-mono text-sm my-4">
                            θ<sub>est</sub> = α · (θ<sub>gyro</sub> + ω · dt) + (1 - α) · θ<sub>accel</sub>
                        </div>
                        <ul class="space-y-2 text-sm mt-2">
                            <li><strong>θ<sub>est</sub>:</strong> Estimated Angle</li>
                            <li><strong>ω:</strong> Gyro rotation rate</li>
                            <li><strong>θ<sub>accel</sub>:</strong> Angle calculated from gravity vector</li>
                            <li><strong>α (alpha):</strong> Tuning factor (typically 0.98 to 0.995)</li>
                        </ul>
                        <p>This simple equation is computationally efficient and runs thousands of times per second on the microcontroller.</p>
                    `
                },
                {
                    id: "practical",
                    title: "9. Practical Tips for Designers & Pilots",
                    content: `
                        <ul class="space-y-3 my-4">
                            <li><strong>Choose rotor size for mission:</strong> larger rotors for heavy payloads and low-speed efficiency; small fast rotors for agility.</li>
                            <li><strong>Reduce payload weight:</strong> every 100 grams increases hover power noticeably on small drones.</li>
                            <li><strong>Balance propellers:</strong> unbalanced props cause vibrations, reduce sensor accuracy, and increase power draw.</li>
                            <li><strong>Tune PID carefully:</strong> fast response requires higher gains but can lead to instability if too aggressive.</li>
                        </ul>
                    `
                }
            ]
        },
        components: {
            title: "Drone Components",
            subtitle: "Essential hardware components that make up a modern drone system: Motors, ESCs, Flight Controllers, and Propellers.",
            sections: [
                {
                    id: "overview",
                    title: "Overview",
                    content: `
                        <p>Every drone is built from a carefully selected set of components that work together to achieve stable, controlled flight. Understanding each component's role is essential for building, maintaining, and troubleshooting drones.</p>
                        <div class="bg-primary/10 border-l-4 border-primary p-4 my-6 rounded">
                            <strong>Quick summary:</strong> The main components include <em>motors</em> (propulsion), <em>ESCs</em> (motor control), <em>flight controllers</em> (brain), <em>propellers</em> (thrust generation), <em>battery</em> (power), and <em>frame</em> (structure).
                        </div>
                    `
                },
                {
                    id: "motors",
                    title: "1. Brushless Motors",
                    content: `
                        <p>Brushless DC motors are the standard for modern drones due to their efficiency, power, and reliability.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Key Specifications</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>KV Rating:</strong> RPM per volt. Higher KV = faster spinning, lower torque. Lower KV = slower spinning, higher torque.</li>
                            <li><strong>Stator Size:</strong> Expressed as XXYY (e.g., 2207). First two digits = stator diameter (mm), last two = stator height (mm).</li>
                            <li><strong>Power Rating:</strong> Maximum wattage the motor can handle continuously.</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Motor Selection Tips</h3>
                        <ul class="space-y-2 my-4">
                            <li>Racing drones: High KV (2300-2600) with smaller props for quick response</li>
                            <li>Freestyle/cruising: Medium KV (1800-2400) for balanced performance</li>
                            <li>Cinematic/heavy lift: Low KV (1000-1500) with larger props for efficiency and smooth flight</li>
                        </ul>
                    `
                },
                {
                    id: "escs",
                    title: "2. Electronic Speed Controllers (ESCs)",
                    content: `
                        <p>ESCs regulate motor speed by converting DC power from the battery into three-phase AC power, precisely controlling motor rotation.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">ESC Features</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>Current Rating:</strong> Maximum continuous amperage (e.g., 30A, 45A, 60A). Always leave 20-30% headroom.</li>
                            <li><strong>Firmware:</strong> BLHeli_S, BLHeli_32, or AM32 - determines features and performance.</li>
                            <li><strong>PWM Frequency:</strong> Higher frequencies (48kHz, 96kHz) provide smoother motor control.</li>
                            <li><strong>DSHOT Protocol:</strong> Digital protocol (DSHOT150, 300, 600, 1200) for faster, more reliable communication.</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">4-in-1 vs Individual ESCs</h3>
                        <p><strong>4-in-1 ESCs:</strong> All four ESCs on one board. Cleaner build, less wiring, but if one fails, you lose all.</p>
                        <p><strong>Individual ESCs:</strong> Separate units for each motor. More wiring, but failure affects only one motor.</p>
                    `
                },
                {
                    id: "flight-controller",
                    title: "3. Flight Controller (FC)",
                    content: `
                        <p>The flight controller is the brain of the drone. It processes sensor data and sends commands to ESCs to maintain stable flight.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Core Components</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>Gyroscope:</strong> Measures angular velocity (rotation rate) on all three axes.</li>
                            <li><strong>Accelerometer:</strong> Measures linear acceleration and helps determine orientation.</li>
                            <li><strong>Barometer:</strong> Measures air pressure for altitude hold (optional).</li>
                            <li><strong>Magnetometer/Compass:</strong> For heading hold and GPS navigation (optional).</li>
                            <li><strong>Processor:</strong> F4, F7, or H7 chips determine processing power and capability.</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Flight Controller Firmware</h3>
                        <p><strong>Betaflight:</strong> Most popular for FPV racing and freestyle. Highly tunable.</p>
                        <p><strong>iNav:</strong> Best for GPS navigation, long-range, and autonomous flight.</p>
                        <p><strong>ArduPilot/PX4:</strong> Advanced autonomous missions, used in commercial applications.</p>
                        <p><strong>KISS:</strong> Simple, "keep it super simple" approach with excellent stock tune.</p>
                    `
                },
                {
                    id: "propellers",
                    title: "4. Propellers",
                    content: `
                        <p>Propellers convert motor rotation into thrust. Their design significantly impacts flight characteristics.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Propeller Specifications</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>Size:</strong> Diameter × Pitch (e.g., 5×4.3 = 5-inch diameter, 4.3-inch theoretical pitch)</li>
                            <li><strong>Blade Count:</strong> 2-blade (efficient), 3-blade (balanced), 4+ blade (high thrust, less efficient)</li>
                            <li><strong>Material:</strong> Plastic (cheap, breaks easily), Carbon Fiber (durable, expensive), Polycarbonate (middle ground)</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Choosing Propellers</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>High pitch:</strong> More speed, more amp draw, more aggressive feel</li>
                            <li><strong>Low pitch:</strong> Better efficiency, smoother flight, lower amp draw</li>
                            <li><strong>Tri-blade:</strong> Popular for freestyle - good balance of grip and efficiency</li>
                            <li><strong>Bi-blade:</strong> Longer flight times, better for cruising and cinematics</li>
                        </ul>
                    `
                },
                {
                    id: "battery",
                    title: "5. Battery (LiPo)",
                    content: `
                        <p>Lithium Polymer (LiPo) batteries provide high energy density and discharge rates needed for drones.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Battery Specifications</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>Cell Count (S):</strong> 3S = 11.1V, 4S = 14.8V, 6S = 22.2V. Higher voltage = more power.</li>
                            <li><strong>Capacity (mAh):</strong> How much energy stored. 1300mAh typical for 5" freestyle.</li>
                            <li><strong>C Rating:</strong> Discharge rate. 75C on 1300mAh = 97.5A max continuous discharge.</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Battery Safety</h3>
                        <ul class="space-y-2 my-4">
                            <li>Never discharge below 3.0V per cell (3.5V safer)</li>
                            <li>Store at 3.8V per cell (storage voltage)</li>
                            <li>Use LiPo-safe bags for charging and storage</li>
                            <li>Inspect for puffing, damage, or punctures before each use</li>
                        </ul>
                    `
                },
                {
                    id: "frame",
                    title: "6. Frame",
                    content: `
                        <p>The frame provides structural support and protection for all components.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Frame Types</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>X-Frame:</strong> Symmetrical, even motor distribution, most common</li>
                            <li><strong>H-Frame:</strong> Longer arms, more space in center for electronics</li>
                            <li><strong>Stretch-X:</strong> Longer wheelbase, smoother flight, better for cinematic</li>
                            <li><strong>True-X/Dead Cat:</strong> Rear arms angled out for clearer FPV camera view</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Frame Material</h3>
                        <p><strong>Carbon Fiber:</strong> Industry standard. Strong, lightweight, good vibration damping. 3-6mm thickness typical.</p>
                        <p><strong>Aluminum:</strong> Heavier but very durable. Often used for arms.</p>
                        <p><strong>3D Printed:</strong> TPU for camera mounts and bumpers. PLA/PETG for non-critical parts.</p>
                    `
                }
            ]
        },
        "flight-modes": {
            title: "Flight Modes",
            subtitle: "Understanding the different flight modes: Stabilize, Acro, Horizon, GPS modes, and how to use them effectively.",
            sections: [
                {
                    id: "overview",
                    title: "Overview",
                    content: `
                        <p>Flight modes determine how the flight controller interprets your stick inputs and maintains stability. Each mode offers different levels of stabilization and control.</p>
                        <div class="bg-primary/10 border-l-4 border-primary p-4 my-6 rounded">
                            <strong>Quick summary:</strong> Beginners should start with <em>Stabilize/Angle</em> mode, progress to <em>Horizon</em>, and eventually master <em>Acro/Manual</em> for full control and aerobatic capabilities.
                        </div>
                    `
                },
                {
                    id: "stabilize",
                    title: "1. Stabilize Mode (Angle/Level)",
                    content: `
                        <p>Stabilize mode is the most beginner-friendly flight mode. The drone automatically levels itself when you release the sticks.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">How It Works</h3>
                        <ul class="space-y-2 my-4">
                            <li>Flight controller maintains level attitude using accelerometer data</li>
                            <li>Stick inputs control the angle of tilt (up to a maximum, typically 50-60°)</li>
                            <li>Releasing sticks returns drone to level flight automatically</li>
                            <li>Prevents the drone from flipping over</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Best For</h3>
                        <ul class="space-y-2 my-4">
                            <li>Complete beginners learning basic controls</li>
                            <li>Smooth cinematic footage</li>
                            <li>Flying in tight spaces where you need assurance</li>
                            <li>Line-of-sight (LOS) flying</li>
                        </ul>
                        <div class="bg-yellow-500/10 border-l-4 border-yellow-500 p-4 my-6 rounded">
                            <strong>Note:</strong> In stabilize mode, you cannot perform flips or rolls. The drone will always try to level itself.
                        </div>
                    `
                },
                {
                    id: "acro",
                    title: "2. Acro Mode (Manual/Rate)",
                    content: `
                        <p>Acro (acrobatic) mode provides full manual control. This is the mode used by experienced FPV pilots and racers.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">How It Works</h3>
                        <ul class="space-y-2 my-4">
                            <li>Stick inputs control rotation rate (degrees per second), not angle</li>
                            <li>No auto-leveling - drone maintains whatever orientation you put it in</li>
                            <li>Full 360° rotation capability on all axes</li>
                            <li>Relies purely on gyroscope, ignores accelerometer for attitude</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Best For</h3>
                        <ul class="space-y-2 my-4">
                            <li>FPV racing and freestyle flying</li>
                            <li>Aerobatic maneuvers (flips, rolls, power loops)</li>
                            <li>Precise control in tight racing scenarios</li>
                            <li>Fast, dynamic flying</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Learning Acro</h3>
                        <ul class="space-y-2 my-4">
                            <li>Practice in a simulator first (Liftoff, DRL Sim, Velocidrone)</li>
                            <li>Start with low rates (300-400°/s) and increase gradually</li>
                            <li>Focus on small movements - smooth is fast</li>
                            <li>Learn to recognize orientation purely from FPV camera</li>
                        </ul>
                    `
                },
                {
                    id: "horizon",
                    title: "3. Horizon Mode",
                    content: `
                        <p>Horizon mode is a hybrid between Stabilize and Acro, offering the best of both worlds.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">How It Works</h3>
                        <ul class="space-y-2 my-4">
                            <li>Behaves like Stabilize mode with small stick movements (auto-levels)</li>
                            <li>Acts like Acro mode with full stick deflection (allows flips/rolls)</li>
                            <li>Smooth transition between the two modes based on stick position</li>
                            <li>Returns to level when sticks are centered</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Best For</h3>
                        <ul class="space-y-2 my-4">
                            <li>Transitioning from Stabilize to Acro mode</li>
                            <li>Freestyle with occasional tricks but wanting auto-level safety</li>
                            <li>Pilots who want maximum versatility</li>
                            <li>Flying in varying conditions</li>
                        </ul>
                        <div class="bg-blue-500/10 border-l-4 border-blue-500 p-4 my-6 rounded">
                            <strong>Tip:</strong> Many pilots use Horizon mode as their main flight mode because it allows creativity while maintaining a safety net.
                        </div>
                    `
                },
                {
                    id: "gps-modes",
                    title: "4. GPS Flight Modes",
                    content: `
                        <p>GPS modes use satellite positioning for advanced autonomous features. Common in camera drones and long-range aircraft.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Position Hold (Loiter)</h3>
                        <ul class="space-y-2 my-4">
                            <li>Maintains current GPS position and altitude automatically</li>
                            <li>Compensates for wind drift</li>
                            <li>Perfect for aerial photography/videography</li>
                            <li>Allows you to take hands off controls completely</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Return to Home (RTH)</h3>
                        <ul class="space-y-2 my-4">
                            <li>Automatically flies back to launch point</li>
                            <li>Triggered manually or by low battery/signal loss</li>
                            <li>Climbs to safe altitude before returning</li>
                            <li>Essential safety feature for long-range flights</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Waypoint/Mission Mode</h3>
                        <ul class="space-y-2 my-4">
                            <li>Pre-programmed flight paths with GPS coordinates</li>
                            <li>Autonomous surveying, mapping, and inspection</li>
                            <li>Used in commercial and agricultural applications</li>
                            <li>Can include altitude, speed, and camera control</li>
                        </ul>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Follow Me</h3>
                        <ul class="space-y-2 my-4">
                            <li>Drone tracks GPS transmitter (usually in controller or phone)</li>
                            <li>Maintains set distance and altitude from subject</li>
                            <li>Great for action sports filming</li>
                            <li>Requires good GPS lock and clear flight path</li>
                        </ul>
                    `
                },
                {
                    id: "other-modes",
                    title: "5. Other Flight Modes",
                    content: `
                        <h3 class="text-xl font-semibold mt-6 mb-3">Altitude Hold</h3>
                        <p>Uses barometer to maintain constant altitude. Throttle stick controls climb/descent rate. Useful for beginners who struggle with altitude management.</p>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Headless Mode</h3>
                        <p>Controls relative to pilot position, not drone orientation. Forward is always away from you. Generally not recommended as it prevents learning proper orientation.</p>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Air Mode</h3>
                        <p>Not a primary flight mode, but a feature in Acro/Horizon. Keeps PID stabilization active at zero throttle, allowing low-throttle tricks and better control during freestyle.</p>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Turtle Mode (Flip Over After Crash)</h3>
                        <p>Allows you to flip the drone right-side-up after a crash by reversing motor directions. Essential for FPV racing/freestyle to avoid walking to retrieve drone.</p>
                    `
                },
                {
                    id: "choosing-mode",
                    title: "6. Choosing the Right Mode",
                    content: `
                        <h3 class="text-xl font-semibold mt-6 mb-3">Progression Path</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>Week 1-2:</strong> Stabilize mode only. Focus on basic movements and orientation.</li>
                            <li><strong>Week 3-4:</strong> Introduce Horizon mode. Practice smooth flying with occasional flips.</li>
                            <li><strong>Week 5-8:</strong> Begin Acro mode in simulator, then transfer to real drone with low rates.</li>
                            <li><strong>Month 3+:</strong> Primarily Acro mode. Increase rates as skill improves.</li>
                        </ul>
                        
                        <div class="bg-green-500/10 border-l-4 border-green-500 p-4 my-6 rounded">
                            <strong>Pro Tip:</strong> Many experienced pilots keep Stabilize mode on a switch for emergency situations or when precision positioning is needed. Don't think of it as "training wheels" - it's another tool in your kit.
                        </div>
                    `
                }
            ]
        },
        safety: {
            title: "Safety & Regulations",
            subtitle: "Essential safety practices and regulatory requirements for responsible drone operation.",
            sections: [
                {
                    id: "overview",
                    title: "Overview",
                    content: `
                        <p>Safe and legal drone operation protects you, others, and the future of the hobby. Regulations vary by country, but the principles of safety are universal.</p>
                        <div class="bg-primary/10 border-l-4 border-primary p-4 my-6 rounded">
                            <strong>Important:</strong> This guide provides general information. Always check your local regulations before flying. Rules change frequently, and you are responsible for compliance.
                        </div>
                    `
                },
                {
                    id: "pre-flight",
                    title: "1. Pre-Flight Safety Checks",
                    content: `
                        <p>Never skip pre-flight checks. A systematic approach prevents most accidents.</p>
                        <h3 class="text-xl font-semibold mt-6 mb-3">Physical Inspection</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>Frame:</strong> Check for cracks, loose screws, or damaged carbon fiber</li>
                            <li><strong>Propellers:</strong> Inspect for chips, cracks, or bends. Replace if damaged.</li>
                            <li><strong>Motors:</strong> Spin freely without grinding or resistance. Check bell tightness.</li>
                            <li><strong>Battery:</strong> No puffing, damage, or loose connections. Check voltage.</li>
                            <li><strong>Wiring:</strong> No exposed wires, secure connections, no heat damage</li>
                        </ul>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Electronics Check</h3>
                        <ul class="space-y-2 my-4">
                            <li>Verify correct flight mode is selected</li>
                            <li>Test arm/disarm switch</li>
                            <li>Confirm all switches and channels respond correctly</li>
                            <li>Check GPS lock if using GPS modes (10+ satellites)</li>
                            <li>Verify OSD displays correct voltage</li>
                        </ul>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Environmental Assessment</h3>
                        <ul class="space-y-2 my-4">
                            <li>Wind speed and direction - know your limits</li>
                            <li>Weather conditions - avoid rain, snow, extreme temperatures</li>
                            <li>Check for obstacles, people, animals in the area</li>
                            <li>Identify safe landing zones and emergency landing spots</li>
                            <li>Ensure adequate visibility and lighting</li>
                        </ul>
                    `
                },
                {
                    id: "flight-safety",
                    title: "2. During Flight Safety",
                    content: `
                        <h3 class="text-xl font-semibold mt-6 mb-3">Core Safety Rules</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>Line of sight:</strong> Maintain visual contact unless certified for FPV/BVLOS</li>
                            <li><strong>Altitude limits:</strong> Stay below 400ft (120m) AGL in most jurisdictions</li>
                            <li><strong>People:</strong> Never fly directly over people or moving vehicles</li>
                            <li><strong>Airports:</strong> Stay at least 5 miles (8km) away, or follow local rules</li>
                            <li><strong>Emergency aircraft:</strong> Land immediately if helicopters/aircraft approach</li>
                        </ul>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Battery Management</h3>
                        <ul class="space-y-2 my-4">
                            <li>Land with 20-30% battery remaining (never below 3.5V per cell)</li>
                            <li>Set low voltage alarms/warnings in OSD</li>
                            <li>Account for wind - you need more battery to return against wind</li>
                            <li>Cold weather reduces battery performance significantly</li>
                        </ul>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Environmental Awareness</h3>
                        <ul class="space-y-2 my-4">
                            <li>Watch for birds - they may attack drones defending territory</li>
                            <li>Avoid flying in fog, clouds, or precipitation</li>
                            <li>Be aware of magnetic interference near power lines, buildings</li>
                            <li>Wind speed increases with altitude</li>
                        </ul>
                        
                        <div class="bg-red-500/10 border-l-4 border-red-500 p-4 my-6 rounded">
                            <strong>Emergency Protocol:</strong> If you lose control or something goes wrong, immediately cut throttle and disarm. Better to have a controlled crash than unpredictable flight.
                        </div>
                    `
                },
                {
                    id: "regulations",
                    title: "3. Registration & Regulations",
                    content: `
                        <p>Most countries now require drone registration and pilot certification for certain operations.</p>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">United States (FAA)</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>Recreational:</strong> Register drones 250g+. Take TRUST test (free, online).</li>
                            <li><strong>Part 107 (Commercial):</strong> Pass FAA written exam. Required for any commercial use.</li>
                            <li><strong>Remote ID:</strong> Required for most drones from 2024. Broadcasts identity and location.</li>
                            <li><strong>Night flying:</strong> Part 107 holders can fly at night with anti-collision lighting.</li>
                        </ul>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">European Union (EASA)</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>Open Category:</strong> Drones under 25kg. Divided into A1, A2, A3 subcategories.</li>
                            <li><strong>Operator Registration:</strong> Required for drones 250g+ or with cameras.</li>
                            <li><strong>Pilot Competency:</strong> Online training for A1/A3, exam required for A2.</li>
                            <li><strong>C-Class Marking:</strong> New drones must have C0-C4 classification markings.</li>
                        </ul>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">United Kingdom (CAA)</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>Operator ID:</strong> Register if drone is 250g+ or has a camera.</li>
                            <li><strong>Flyer ID:</strong> Pass online education test (£10.87, valid 3 years).</li>
                            <li><strong>Drone Zones:</strong> Check NATS Drone Assist app before flying.</li>
                        </ul>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Other Regions</h3>
                        <p>Canada (Transport Canada), Australia (CASA), India (DGCA), and other countries have their own regulatory frameworks. Research requirements in your jurisdiction.</p>
                    `
                },
                {
                    id: "privacy-ethics",
                    title: "4. Privacy & Ethics",
                    content: `
                        <p>Drones with cameras raise legitimate privacy concerns. Responsible pilots respect others' privacy and property.</p>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Best Practices</h3>
                        <ul class="space-y-2 my-4">
                            <li>Don't fly over private property without permission</li>
                            <li>Avoid filming people who haven't consented</li>
                            <li>Don't fly near schools, hospitals, or sensitive facilities</li>
                            <li>Be transparent about your activities when questioned</li>
                            <li>Delete footage if asked by property owners</li>
                        </ul>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Public Perception</h3>
                        <p>Remember that every drone pilot represents the community. Negative experiences lead to more restrictions. Be courteous, explain what you're doing, and demonstrate professionalism.</p>
                        
                        <div class="bg-blue-500/10 border-l-4 border-blue-500 p-4 my-6 rounded">
                            <strong>Golden Rule:</strong> Fly as if everyone is watching. Would you be comfortable explaining your flight to law enforcement or posting it publicly? If not, reconsider.
                        </div>
                    `
                },
                {
                    id: "insurance",
                    title: "5. Insurance & Liability",
                    content: `
                        <h3 class="text-xl font-semibold mt-6 mb-3">Why Insurance Matters</h3>
                        <p>Drone crashes can cause property damage, injuries, or worse. Standard homeowner's/renter's insurance typically doesn't cover drone operations.</p>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Insurance Options</h3>
                        <ul class="space-y-2 my-4">
                            <li><strong>Liability Insurance:</strong> Covers damage to others' property or injuries. Essential for commercial operators.</li>
                            <li><strong>Hull Insurance:</strong> Covers damage to your own drone. Optional but recommended for expensive builds.</li>
                            <li><strong>Membership Organizations:</strong> AMA (US), BMFA (UK) include liability insurance with membership.</li>
                        </ul>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Risk Mitigation</h3>
                        <ul class="space-y-2 my-4">
                            <li>Fly in designated areas away from people and property</li>
                            <li>Maintain your equipment properly</li>
                            <li>Don't fly beyond your skill level</li>
                            <li>Use propeller guards when flying near people</li>
                            <li>Keep detailed flight logs and maintenance records</li>
                        </ul>
                    `
                },
                {
                    id: "community",
                    title: "6. Community & Education",
                    content: `
                        <h3 class="text-xl font-semibold mt-6 mb-3">Join the Community</h3>
                        <ul class="space-y-2 my-4">
                            <li>Local flying clubs offer mentorship and safe flying spaces</li>
                            <li>Online forums (Reddit r/Multicopter, RCGroups, FPV Discord servers)</li>
                            <li>Attend races and events to learn from experienced pilots</li>
                            <li>Share knowledge and help newcomers</li>
                        </ul>
                        
                        <h3 class="text-xl font-semibold mt-6 mb-3">Continuous Learning</h3>
                        <ul class="space-y-2 my-4">
                            <li>Stay updated on regulation changes</li>
                            <li>Learn from incidents and accidents (yours and others')</li>
                            <li>Practice in simulators to improve skills safely</li>
                            <li>Take advanced courses for specific use cases (cinematography, inspection, etc.)</li>
                        </ul>
                        
                        <div class="bg-green-500/10 border-l-4 border-green-500 p-4 my-6 rounded">
                            <strong>Remember:</strong> The drone community thrives when we self-regulate responsibly. Your actions affect everyone's access to the hobby. Fly safe, fly legal, fly respectfully.
                        </div>
                    `
                }
            ]
        }
    }

    return content[slug] || null
}

export default async function TheoryDetailPage({
    params,
}: {
    params: Promise<{ slug: string }>
}) {
    const { slug } = await params
    const theoryData = getTheoryContent(slug)

    // Fallback for topics without detailed content
    if (!theoryData) {
        const title = slug.replace(/-/g, " ").replace(/\b\w/g, (l) => l.toUpperCase())

        return (
            <div className="min-h-screen bg-gradient-to-b from-background to-muted/20">
                <div className="container max-w-5xl mx-auto py-12 px-4 md:px-6 lg:px-8">
                    <Link href="/theory">
                        <Button variant="ghost" className="mb-8 pl-0 hover:bg-transparent hover:text-primary">
                            <ArrowLeft className="mr-2 h-4 w-4" />
                            Back to Theory
                        </Button>
                    </Link>

                    <article className="space-y-12">
                        <header className="space-y-6 border-b pb-8">
                            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text">
                                {title}
                            </h1>
                            <p className="text-xl md:text-2xl text-muted-foreground leading-relaxed max-w-3xl">
                                This is a detailed guide about {title}. Here we explore the fundamental concepts,
                                components, and practical applications in the world of drones.
                            </p>
                        </header>

                        <section className="space-y-6">
                            <h2 className="text-3xl md:text-4xl font-bold tracking-tight">Introduction</h2>
                            <div className="prose prose-lg prose-neutral dark:prose-invert max-w-none">
                                <p className="text-base md:text-lg leading-relaxed">
                                    Understanding {title} is crucial for any drone enthusiast. Whether you are building
                                    a racing quadcopter or a heavy-lift camera drone, these principles apply across all platforms.
                                </p>
                            </div>
                        </section>

                        <div className="bg-muted/50 rounded-lg p-6 my-8">
                            <h3 className="text-lg font-semibold mb-2">💡 Pro Tip</h3>
                            <p className="text-sm leading-relaxed">
                                Always test your configurations in a safe, controlled environment before attempting
                                advanced maneuvers or flying in challenging conditions.
                            </p>
                        </div>
                    </article>
                </div>
            </div>
        )
    }

    return (
        <div className="min-h-screen bg-gradient-to-b from-background to-muted/20">
            <div className="container max-w-5xl mx-auto py-12 px-4 md:px-6 lg:px-8">
                <Link href="/theory">
                    <Button variant="ghost" className="mb-8 pl-0 hover:bg-transparent hover:text-primary">
                        <ArrowLeft className="mr-2 h-4 w-4" />
                        Back to Theory
                    </Button>
                </Link>

                <article className="space-y-12">
                    <header className="space-y-6 border-b pb-8">
                        <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text">
                            {theoryData.title}
                        </h1>
                        <p className="text-xl md:text-2xl text-muted-foreground leading-relaxed max-w-3xl">
                            {theoryData.subtitle}
                        </p>
                    </header>

                    {theoryData.sections.map((section: any) => (
                        <section key={section.id} id={section.id} className="space-y-6 scroll-mt-20">
                            <h2 className="text-3xl md:text-4xl font-bold tracking-tight">{section.title}</h2>
                            <div
                                className="prose prose-lg prose-neutral dark:prose-invert max-w-none"
                                dangerouslySetInnerHTML={{ __html: section.content }}
                            />
                        </section>
                    ))}

                    <div className="bg-muted/50 rounded-lg p-6 my-8">
                        <h3 className="text-lg font-semibold mb-2">💡 Pro Tip</h3>
                        <p className="text-sm leading-relaxed">
                            Always test your configurations in a safe, controlled environment before attempting
                            advanced maneuvers or flying in challenging conditions. Start with basic maneuvers and gradually progress to more complex flight patterns.
                        </p>
                    </div>
                </article>
            </div>
        </div>
    )
}
